[package]
name = "fsr-tui"
version.workspace = true
edition.workspace = true

[dependencies]
fsr-types = { path = "../fsr-types" }
fsr-fixed = { path = "../fsr-fixed" }
fsr-ttcp = { path = "../fsr-ttcp" }
ratatui = "0.26"
crossterm = "0.27"
serde = { workspace = true }
serde_json = { workspace = true }
anyhow = { workspace = true }
